### ISSUE TITLE
WHERE IS THE SEARCH?

### ISSUE THREAD

**Issue by dok** [docstrap/docstrap#111] opened 2015-07-21 23:40 UTC
It says docstrap supports the search but I don't see any documentation on how to set it up. 

Thanks

**Comment by M3lkior** [comment] 2015-07-24 08:09
+1

**Comment by devanecondition** [comment] 2015-07-24 17:10
+1

**Comment by fisch0920** [comment] 2015-08-19 09:25
+1

**Comment by kushdilip** [comment] 2015-09-11 12:32
:+1:

**Comment by kushdilip** [comment] 2015-09-11 12:33
+1

**Comment by marcelopm** [comment] 2015-12-02 01:59
+1

**Comment by lukeapage** [comment] 2015-12-05 17:20
Anyone know if docstrap ever supported search? or is this an enhancement?

**Comment by lukeapage** [comment] 2015-12-05 17:37
possible duplicate of #63

**Comment by lukeapage** [comment] 2015-12-07 20:59
its implemented here: #136

Anyone want to try out the PR and see if it works?

**Comment by lukeapage** [comment] 2015-12-11 06:22
done. will be in the next release.

**Closed by lukeapage** 2015-12-11 06:22 UTC
Labels: bug, enhancement

**Comment by gusmatlis** [comment] 2016-04-11 20:49
Team, this search is partially useful as it has lost the ability to take you the exact location within the page as the old page search used to do.  
What we need is to add additional functionality so once the link is clicked on the results pop-up, the new page is opened and scrolled to the location of the first instance. Otherwise, you still have to d a page search to fund the exact location. Which defeats the purpose of a search engine.  Ideally, there would also be a next button  so you can scroll trough all of the found instances within the page... as any standard search would...
