### ISSUE TITLE
Too long file name, making it hard to work with package on linux (255 char max on a path)

### ISSUE THREAD

**Issue by JostBaron** [docstrap/docstrap#109] opened 2015-07-09 09:19 UTC
When installing the package 'grunt-jsdoc', it installs this package as dependency, in this path:

    <project-root>/node_modules/grunt-jsdoc/node_modules/ink-docstrap/

This creates the file

    <project-root>/node_modules/grunt-jsdoc/node_modules/ink-docstrap/themes/paper/module-documents_probe.This%2520is%2520not%2520actually%2520a%2520class,%2520but%2520an%2520artifact%2520of%2520the%2520documentation%2520system.html

This filename has 214 characters alone for the path under the project root, leaving only 41 characters for the path to the project. If the path to the project has more than these 41 characters, the error `npm ERR! Error: ENAMETOOLONG, open '<complete path>'` is thrown.

The file system is ext4, so nothing old and dusty.

**Comment by perry-mitchell** [comment] 2015-07-27 08:20
Has there been any progress on this? I'm encountering the same issue, and it seems many others are posting similar issues:

https://github.com/terryweiss/docstrap/issues/103
https://github.com/krampstudio/grunt-jsdoc/issues/116

**Comment by bobholt** [comment] 2015-08-18 13:39
This is due to the ink-docstrap dependency running docs against this line, which generates the filename causing the ENAMETOOLONG error:

https://github.com/terryweiss/docstrap/blob/master/fixtures/documents/probe.js#L1004

See also:
- https://github.com/krampstudio/grunt-jsdoc/issues/142
- https://github.com/terryweiss/docstrap/issues/103

**Comment by joh-klein** [comment] 2015-09-15 13:12
Why isn't this being fixed?

**Comment by gert-fresh** [comment] 2015-09-24 09:51
npm ERR! ENAMETOOLONG: name too long, open '/home/xxx/xxx/xxx/test/node_modules/ink-docstrap/themes/paper/module-documents_probe.This%2520is%2520not%2520actually%2520a%2520class,%2520but%2520an%2520artifact%2520of%2520the%2520documentation%2520system.html'

I have this issue too, on an encrypted (ecryptfs) ext4 partition on Ubuntu 15.04.

**Comment by davidmaxwaterman** [comment] 2015-09-28 08:20
This is blocking me too.

**Comment by gert-fresh** [comment] 2015-09-28 09:36
Please review and/or merge: https://github.com/terryweiss/docstrap/pull/114

**Comment by lukeapage** [comment] 2015-12-07 20:36
This should be fixed in the 0.5.3 release (out now) - the file doesn't seem to be generated for me. I'm going to exclude the themes directory from npm because its just generated html for docs - not needed for publishing on npm.

Can someone verify?

**Closed** 2015-12-07 20:36 UTC
Labels: bug

**Comment by terryweiss** [comment] 2015-12-07 20:50
I can confirm it is only for local docs in the event you are not connected and want to see the themes. I doubt it was ever really used.

**Comment by gert-fresh** [comment] 2015-12-08 09:41
I can confirm too it's been fixed.
