### ISSUE TITLE
Add a search engine

### ISSUE THREAD

**Issue by herau** [docstrap/docstrap#29] opened 2014-02-18 09:48 UTC
By default, JSdoc has not search engine. It would be nice to have this kind of feature !
Or maybe use an existing JSdoc plugin ?

**Comment by IjinPL** [comment] 2015-01-07 21:58
+1

**Comment by purtuga** [comment] 2015-04-09 00:45
+1

Anyone start this yet? 
I'm thinking about it.  I'm a very big user of this template and currently use it on a very large project. Global search is something that would really be great.

**Comment by daprahamian** [comment] 2015-08-13 17:57
:+1:

**Comment by lukeapage** [comment] 2015-12-07 21:04
See #111 (closing as duplicate of) and PR - #136 help testing the search would be welcome.

**Closed by lukeapage** 2015-12-07 21:04 UTC
Labels: enhancement

**Comment by gusmatlis** [comment] 2016-04-11 20:50
Team, this search is partially useful as it has lost the ability to take you the exact location within the page as the old page search used to do.  
What we need is to add additional functionality so once the link is clicked on the results pop-up, the new page is opened and scrolled to the location of the first instance. Otherwise, you still have to d a page search to fund the exact location. Which defeats the purpose of a search engine.  Ideally, there would also be a next button  so you can scroll trough all of the found instances within the page... as any standard search would...
